import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#f3f4f6",
  },
  header: {
    backgroundColor: "#1f9f4a",
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
  },
  minutesPill: {
    width: 44,
    height: 44,
    borderRadius: 8,
    backgroundColor: "rgba(255,255,255,0.14)",
    alignItems: "center",
    justifyContent: "center",
  },
  minutesValue: {
    color: "#ffffff",
    fontSize: 17,
    fontWeight: "800",
    lineHeight: 18,
  },
  minutesLabel: {
    color: "#ffffff",
    fontSize: 9,
    fontWeight: "700",
    marginTop: 2,
  },
  locationWrap: {
    flex: 1,
    marginLeft: 10,
  },
  locationTitle: {
    color: "#ffffff",
    fontSize: 22,
    fontWeight: "800",
    lineHeight: 24,
  },
  locationSubtitle: {
    color: "rgba(255,255,255,0.84)",
    fontSize: 12,
    fontWeight: "500",
    marginTop: 2,
  },
  profileDot: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
  },
  profileDotInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: "#1f9f4a",
  },
  listContent: {
    paddingBottom: 20,
  },
  sectionWrap: {
    marginTop: 14,
    paddingHorizontal: 14,
  },
  sectionHeaderWrap: {
    marginBottom: 10,
  },
  sectionTitle: {
    color: "#171717",
    fontSize: 32,
    fontWeight: "800",
    lineHeight: 36,
  },
  sectionSubtitle: {
    color: "#6d6d6d",
    fontSize: 12,
    marginTop: 2,
    fontWeight: "500",
  },
  bundleCard: {
    backgroundColor: "#ffffff",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#ececec",
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
  },
  bundleTextWrap: {
    flex: 1,
    paddingRight: 8,
  },
  bundleTitle: {
    color: "#171717",
    fontSize: 16,
    fontWeight: "800",
    lineHeight: 20,
  },
  bundleSubtitle: {
    color: "#6d6d6d",
    marginTop: 6,
    fontSize: 12,
    lineHeight: 17,
  },
  bundleButton: {
    marginTop: 10,
    alignSelf: "flex-start",
    borderRadius: 12,
    backgroundColor: "#167d3b",
    paddingVertical: 7,
    paddingHorizontal: 12,
  },
  bundleButtonText: {
    color: "#ffffff",
    fontWeight: "700",
    fontSize: 12,
  },
  bundleArt: {
    width: 100,
    height: 96,
    borderRadius: 14,
    backgroundColor: "#e8f6ec",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#d4ecd9",
  },
  bundleArtImage: {
    width: 84,
    height: 84,
    borderRadius: 12,
  },
  serviceGridContent: {
    paddingBottom: 2,
  },
  serviceRow: {
    justifyContent: "space-between",
  },
  serviceCard: {
    width: "31.5%",
    backgroundColor: "#eef0f1",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e1e2e3",
    padding: 8,
    marginBottom: 10,
  },
  serviceArt: {
    width: "100%",
    height: 48,
    borderRadius: 9,
    backgroundColor: "#dce2de",
    alignItems: "center",
    justifyContent: "center",
  },
  serviceArtImage: {
    width: "100%",
    height: "100%",
    borderRadius: 9,
  },
  serviceName: {
    marginTop: 8,
    color: "#1c1c1c",
    fontSize: 12,
    lineHeight: 14,
    fontWeight: "600",
    minHeight: 30,
  },
  serviceBottomRow: {
    marginTop: 6,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  badge: {
    backgroundColor: "#ff6f61",
    borderRadius: 6,
    paddingHorizontal: 5,
    paddingVertical: 2,
  },
  badgeText: {
    color: "#ffffff",
    fontSize: 9,
    fontWeight: "700",
  },
  addCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1.5,
    borderColor: "#2caa58",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff",
  },
  addCircleText: {
    color: "#2caa58",
    fontSize: 14,
    fontWeight: "700",
    lineHeight: 14,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.3)",
    justifyContent: "flex-end",
  },
  modalSheet: {
    backgroundColor: "#ffffff",
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 24,
  },
  modalHandle: {
    alignSelf: "center",
    width: 42,
    height: 4,
    borderRadius: 999,
    backgroundColor: "#d8d8d8",
    marginBottom: 14,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
  },
  modalImage: {
    width: 60,
    height: 60,
    borderRadius: 10,
  },
  modalTitleWrap: {
    flex: 1,
    marginLeft: 12,
  },
  modalTitle: {
    color: "#171717",
    fontSize: 17,
    fontWeight: "800",
  },
  modalSubtitle: {
    color: "#5f5f5f",
    fontSize: 12,
    marginTop: 4,
    lineHeight: 17,
  },
  modalAddButton: {
    marginTop: 16,
    backgroundColor: "#1f9f4a",
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
  },
  modalAddButtonText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "700",
  },
});
